"""
Backward-compatibility shim for lumen.core.

The implementation has been split into the lumen/core/ package.
This module re-exports everything so that existing imports of the form

    from lumen.core import LumenDict, encode_varint, ...

continue to work without modification.
"""

from lumen.core import *  # noqa: F401, F403
from lumen.core import (  # noqa: F401
    MAGIC,
    S_BITS,
    S_DELTA,
    S_POOL,
    S_RAW,
    S_RLE,
    T_BITS,
    T_BOOL,
    T_DELTA_RAW,
    T_FLOAT,
    T_INT,
    T_LIST,
    T_MAP,
    T_MATRIX,
    T_NULL,
    T_POOL_DEF,
    T_POOL_REF,
    T_RLE,
    T_STR,
    T_STR_TINY,
    T_STRATEGY,
    VERSION,
    LumenDict,
    LumenDictFull,
    __edition__,
    __version__,
    _encode_obj_iterative_text,
    _encode_value_text,
    _format_float,
    _parse_value,
    _text_escape,
    _text_unescape,
    build_pool,
    compute_bits_savings,
    compute_delta_savings,
    compute_rle_savings,
    decode_binary_records,
    decode_text_records,
    decode_varint,
    decode_zigzag,
    deep_eq,
    deep_size,
    detect_column_strategy,
    encode_binary_records,
    encode_text_records,
    encode_varint,
    encode_zigzag,
    estimate_tokens,
    fnv1a,
    fnv1a_str,
    pack_bits,
    pack_bool,
    pack_delta_raw,
    pack_float,
    pack_int,
    pack_null,
    pack_pool_ref,
    pack_rle,
    pack_string,
    unpack_bits,
    unpack_delta_raw,
)
